FROM node:alpine AS build
WORKDIR '/app'
COPY package.json .
RUN npm install
#RUN npm install -g nodemon
#install jtest and supertest
#RUN npm install supertest
#RUN npm install -g jest
COPY SourceCode ./SourceCode
#COPY tests ./tests
COPY webpack.config.js .
#CMD ["npm","run","dev"]
RUN npm run build

FROM node:alpine
WORKDIR '/app'
COPY --from=build /app/build /app/build
EXPOSE 8080 
CMD ["node","/app/build/index.js"]
