name: Deploy application image
on:
 pull_request:
  types:
   - closed
  brances:
   - master
jobs:
  deploy-app:
   if: ${{ github.event.pull_request.merged == true }}
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v1
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - run: docker image build -t mouhebboubaker2/simplewebprod -f Dockerfile.dev .
    - run: docker image push mouhebboubaker2/simplewebprod
