name: Shell Commands

on:
push:
branches:
 - dev
jobs:
 run-shell-command:
  runs-on: ubuntu-latest
  steps:
   -name: echo a string 
    run: echo "Starting" 
   -name: multiline script
    run: |
       node -v
       npm -v
